"""
dashboard.py
Builds a professional 6-sheet Excel dashboard from analysis results.
"""

import pandas as pd
import sqlite3
import os
from openpyxl import Workbook
from openpyxl.styles import (
    Font, PatternFill, Alignment, Border, Side, GradientFill
)
from openpyxl.utils import get_column_letter
from openpyxl.chart import BarChart, LineChart, PieChart, Reference
from openpyxl.chart.series import DataPoint
from openpyxl.formatting.rule import ColorScaleRule, DataBarRule, CellIsRule, FormulaRule


C = {
    "navy":      "1B2A4A",
    "teal":      "0E7C86",
    "orange":    "E05C1A",
    "green":     "1A7A4A",
    "purple":    "5C3D99",
    "red":       "C0392B",
    "yellow":    "F0B429",
    "white":     "FFFFFF",
    "light_bg":  "F4F7FA",
    "mid_bg":    "D9E4EE",
    "dark_text": "1A1A2E",
    "muted":     "6B7280",
    "success":   "D1FAE5",
    "warning":   "FEF3C7",
    "danger":    "FEE2E2",
    "header_alt":"E8EFF6",
}

def fill(hex_color):
    return PatternFill("solid", start_color=hex_color, fgColor=hex_color)

def font(bold=False, size=11, color="1A1A2E", italic=False, name="Calibri"):
    return Font(bold=bold, size=size, color=color, italic=italic, name=name)

def align(h="left", v="center", wrap=False):
    return Alignment(horizontal=h, vertical=v, wrap_text=wrap)

def thin_border(sides="all"):
    s = Side(style="thin", color="C5D1DC")
    d = {"left": s, "right": s, "top": s, "bottom": s} if sides == "all" else {}
    return Border(**{k: s for k in (sides.split(",") if sides != "all" else d)})

def thick_bottom():
    return Border(bottom=Side(style="medium", color="1B2A4A"))

def set_col_widths(ws, widths):
    for col, w in widths.items():
        ws.column_dimensions[col].width = w

def header_row(ws, row, cols, text_color="FFFFFF", bg=C["navy"], size=11):
    for col, (letter, label) in enumerate(cols, 1):
        c = ws.cell(row=row, column=col, value=label)
        c.font      = font(bold=True, color=text_color, size=size)
        c.fill      = fill(bg)
        c.alignment = align("center")
        c.border    = thin_border()

def data_row(ws, row, values, bg="FFFFFF", bold=False, color="1A1A2E"):
    bg_c = C["light_bg"] if row % 2 == 0 else bg
    for col, val in enumerate(values, 1):
        c = ws.cell(row=row, column=col, value=val)
        c.font      = font(bold=bold, color=color)
        c.fill      = fill(bg_c)
        c.alignment = align("center" if col > 1 else "left")
        c.border    = thin_border()

def banner(ws, row, text, span_end, bg=C["navy"], txt="FFFFFF", size=18, merge=True):
    ws.cell(row=row, column=1, value=text).font = font(bold=True, color=txt, size=size)
    if merge:
        ws.merge_cells(start_row=row, start_column=1, end_row=row, end_column=span_end)
    ws.row_dimensions[row].height = 36
    for col in range(1, span_end+1):
        ws.cell(row=row, column=col).fill = fill(bg)
        ws.cell(row=row, column=col).alignment = align("center")

def kpi_tile(ws, row, col, label, value, bg=C["navy"], val_color="FFFFFF"):
    ws.merge_cells(start_row=row,   start_column=col, end_row=row,   end_column=col+1)
    ws.merge_cells(start_row=row+1, start_column=col, end_row=row+1, end_column=col+1)
    ws.row_dimensions[row].height   = 22
    ws.row_dimensions[row+1].height = 32
    lc = ws.cell(row=row,   column=col, value=label)
    vc = ws.cell(row=row+1, column=col, value=value)
    lc.font = font(size=9, color="B0C4D8", italic=True)
    vc.font = font(bold=True, size=18, color=val_color)
    for r in [row, row+1]:
        for c in range(col, col+2):
            ws.cell(r, c).fill      = fill(bg)
            ws.cell(r, c).alignment = align("center")


def load(name):
    return pd.read_csv(f"data/{name}.csv")



def build_kpi(wb):
    ws = wb.create_sheet("📊 KPI Summary")
    ws.sheet_view.showGridLines = False
    ws.sheet_properties.tabColor = C["navy"]
    set_col_widths(ws, {get_column_letter(i): 14 for i in range(1, 15)})
    ws.column_dimensions["A"].width = 3
    ws.row_dimensions[1].height = 6

    # Title banner
    banner(ws, 2, "  OPERATIONS — EXECUTIVE KPI DASHBOARD", 13)
    ws.cell(2,1).font = font(bold=True, color="FFFFFF", size=16)

    # Sub-header
    ws.merge_cells("A3:M3")
    sub = ws.cell(3, 1, "Period: 01 Mar 2024 – 30 Mar 2024   |   Generated by Ops Analytics")
    sub.font      = font(size=9, color="8FADC8", italic=True)
    sub.fill      = fill(C["navy"])
    sub.alignment = align("center")
    ws.row_dimensions[3].height = 18

    kpi = load("kpi_summary").iloc[0]

    # Row 1 KPI tiles
    tiles1 = [
        ("TOTAL ORDERS",        f"{int(kpi['total_orders']):,}",         C["navy"],   "FFFFFF"),
        ("UNITS PICKED",        f"{int(kpi['total_units_picked']):,}",   C["teal"],   "FFFFFF"),
        ("TOTAL GMV",           f"₹{kpi['total_gmv_inr']/1e6:.2f}M",    C["green"],  "FFFFFF"),
        ("OVERALL UPH",         f"{kpi['overall_uph']} u/hr",            C["purple"], "FFFFFF"),
        ("AVG FULFILLMENT",     f"{kpi['avg_fulfillment_min']} min",      C["orange"], "FFFFFF"),
        ("FULFILLMENT RATE",    f"{kpi['fulfillment_rate_pct']:.1f}%",   C["teal"],   "FFFFFF"),
    ]
    ws.row_dimensions[5].height = 8
    r = 6
    for i, (lbl, val, bg, vc) in enumerate(tiles1):
        col = 2 + i*2
        kpi_tile(ws, r, col, lbl, val, bg, vc)
    ws.row_dimensions[r].height   = 24
    ws.row_dimensions[r+1].height = 36

    # Row 2 KPI tiles
    tiles2 = [
        ("AVG DELIVERY COST",   f"₹{kpi['avg_delivery_cost_inr']:.0f}",   "2C3E50", "FFFFFF"),
        ("TOTAL DELIVERY COST", f"₹{kpi['total_delivery_cost_inr']/1e5:.1f}L", "2C3E50", "FFFFFF"),
        ("RETURN RATE",         f"{kpi['return_rate_pct']:.1f}%",           C["red"],  "FFFFFF"),
        ("ACTIVE PICKERS",      "8",                                        C["purple"],"FFFFFF"),
        ("SKUs TRACKED",        "41",                                       C["green"], "FFFFFF"),
        ("ACTIVE ZONES",        "6",                                        C["orange"],"FFFFFF"),
    ]
    ws.row_dimensions[r+3].height = 8
    r2 = r + 4
    for i, (lbl, val, bg, vc) in enumerate(tiles2):
        col = 2 + i*2
        kpi_tile(ws, r2, col, lbl, val, bg, vc)
    ws.row_dimensions[r2].height   = 24
    ws.row_dimensions[r2+1].height = 36

    # Section:Top Performers
    r3 = r2 + 4
    ws.row_dimensions[r3].height = 8
    banner(ws, r3+1, "TOP 5 PICKERS BY UPH", 8, bg=C["teal"], size=12)
    pickers_df = load("picker_uph").head(5)
    hcols = [("A","Picker ID"),("B","Name"),("C","Shift"),("D","Total Orders"),
             ("E","Units Picked"),("F","UPH"),("G","Avg TAT (min)"),("H","Accuracy %")]
    header_row(ws, r3+2, hcols, bg="164B60")
    for i, row_data in pickers_df.iterrows():
        r_excel = r3 + 3 + list(pickers_df.index).index(i)
        vals = [row_data["picker_id"], row_data["name"], row_data["shift"],
                int(row_data["total_orders"]), int(row_data["total_units"]),
                row_data["uph"], row_data["avg_fulfillment_min"], row_data["accuracy_pct"]]
        data_row(ws, r_excel, vals, bg="FFFFFF")

    # Section: Low Stock Alerts
    r4 = r3 + 10
    banner(ws, r4, "⚠  STOCK ALERTS", 8, bg=C["orange"], size=12)
    alerts = load("reorder_alerts").head(6)
    hcols2 = [("A","SKU"),("B","Product"),("C","Category"),("D","Zone"),
              ("E","Current Stock"),("F","Reorder Level"),("G","Shortage"),("H","Alert")]
    header_row(ws, r4+1, hcols2, bg="8B2500")
    for idx, row_data in alerts.iterrows():
        rv = r4 + 2 + list(alerts.index).index(idx)
        vals = [row_data.sku_id, row_data.product_name, row_data.category,
                row_data.storage_zone, int(row_data.current_stock),
                int(row_data.reorder_level), int(row_data.shortage_units), row_data.alert_level]
        alert_bg = "FEE2E2" if "OUT" in str(row_data.alert_level) else "FEF3C7"
        data_row(ws, rv, vals, bg=alert_bg)


def build_picker(wb):
    ws = wb.create_sheet("👷 Picker Productivity")
    ws.sheet_view.showGridLines = False
    ws.sheet_properties.tabColor = C["teal"]
    set_col_widths(ws, {"A":3,"B":10,"C":22,"D":14,"E":13,"F":13,"G":12,"H":14,"I":14,"J":13})
    ws.row_dimensions[1].height = 6

    banner(ws, 2, "PICKER PRODUCTIVITY ANALYSIS", 10, bg=C["teal"], size=15)

    df = load("picker_uph")
    hcols = [("B","Picker ID"),("C","Name"),("D","Shift"),("E","Total Orders"),
             ("F","Total Units"),("G","UPH"),("H","Avg TAT (min)"),("I","Accuracy %"),("J","Experience (Yr)")]

    pickers_raw = pd.read_csv("data/pickers.csv")
    df2 = df.merge(pickers_raw[["picker_id","experience_yr"]], on="picker_id", how="left")

    header_row(ws, 4, hcols, bg=C["teal"])
    for i, row_data in df2.iterrows():
        rv = 5 + i
        uph = row_data["uph"]
        uph_color = C["green"] if uph > 7 else (C["orange"] if uph > 5 else C["red"])
        vals = [row_data["picker_id"], row_data["name"], row_data["shift"],
                int(row_data["total_orders"]), int(row_data["total_units"]),
                uph, row_data["avg_fulfillment_min"], row_data["accuracy_pct"],
                int(row_data["experience_yr"])]
        data_row(ws, rv, vals, bg="FFFFFF")
        # colour UPH cell
        uph_cell = ws.cell(rv, 7)
        uph_cell.fill = fill("D1FAE5" if uph > 7 else ("FEF3C7" if uph > 5 else "FEE2E2"))
        uph_cell.font = font(bold=True, color=uph_color)

    # UPH bar chart
    chart = BarChart()
    chart.type = "bar"
    chart.title = "Units Per Hour (UPH) by Picker"
    chart.y_axis.title = "Picker"
    chart.x_axis.title = "UPH"
    chart.style = 10
    chart.width = 22
    chart.height = 14

    data_ref  = Reference(ws, min_col=7, max_col=7, min_row=4, max_row=4+len(df2))
    cats_ref  = Reference(ws, min_col=3, max_col=3, min_row=5, max_row=4+len(df2))
    chart.add_data(data_ref, titles_from_data=True)
    chart.set_categories(cats_ref)
    ws.add_chart(chart, "B14")

    # Accuracy chart
    chart2 = BarChart()
    chart2.type = "bar"
    chart2.title = "Picking Accuracy (%) by Picker"
    chart2.style = 10
    chart2.width = 22
    chart2.height = 14
    data2 = Reference(ws, min_col=8, max_col=8, min_row=4, max_row=4+len(df2))
    chart2.add_data(data2, titles_from_data=True)
    chart2.set_categories(cats_ref)
    ws.add_chart(chart2, "F14")

    # Legend note
    ws.cell(30, 2, "🟢 UPH > 7 = Excellent   🟡 5–7 = Average   🔴 < 5 = Needs Improvement").font = font(size=10, color=C["muted"], italic=True)


def build_sku(wb):
    ws = wb.create_sheet("📦 SKU Performance")
    ws.sheet_view.showGridLines = False
    ws.sheet_properties.tabColor = C["green"]
    set_col_widths(ws, {"A":3,"B":10,"C":22,"D":14,"E":10,"F":10,"G":13,"H":14,
                        "I":12,"J":14,"K":14})
    ws.row_dimensions[1].height = 6

    banner(ws, 2, "SKU VELOCITY & STOCK HEALTH", 11, bg=C["green"], size=15)

    df = load("sku_velocity")
    hcols = [("B","SKU ID"),("C","Product Name"),("D","Category"),("E","Zone"),
             ("F","Price (₹)"),("G","Units Sold"),("H","Order Count"),
             ("I","Velocity"),("J","Stock Status"),("K","Current Stock")]
    header_row(ws, 4, hcols, bg=C["green"])

    vel_color = {"Fast Mover": "D1FAE5", "Medium Mover": "FEF3C7", "Slow Mover": "FEE2E2"}
    stk_color = {"OK": "D1FAE5", "Low Stock": "FEF3C7",
                 "REORDER NOW": "FEE2E2", "OUT OF STOCK": "FEE2E2"}

    for i, row_data in df.iterrows():
        rv = 5 + i
        vals = [row_data.sku_id, row_data.product_name, row_data.category,
                row_data.storage_zone, round(row_data.price_inr,2),
                int(row_data.units_sold) if pd.notna(row_data.units_sold) else 0,
                int(row_data.order_count) if pd.notna(row_data.order_count) else 0,
                row_data.velocity_tag, row_data.stock_status, int(row_data.current_stock)]
        data_row(ws, rv, vals, bg="FFFFFF")
        ws.cell(rv, 9).fill  = fill(vel_color.get(str(row_data.velocity_tag), "FFFFFF"))
        ws.cell(rv, 10).fill = fill(stk_color.get(str(row_data.stock_status), "FFFFFF"))
        ws.cell(rv, 9).font  = font(bold=True)
        ws.cell(rv, 10).font = font(bold=True)

    # Category revenue pie
    cat_df = load("category_tat")[["category","total_revenue_inr"]]
    # Write mini table for chart
    ws.cell(5, 13, "Category").font = font(bold=True, color="FFFFFF")
    ws.cell(5, 13).fill = fill(C["navy"])
    ws.cell(5, 14, "Revenue (₹)").font = font(bold=True, color="FFFFFF")
    ws.cell(5, 14).fill = fill(C["navy"])
    for j, row_data in cat_df.iterrows():
        ws.cell(6+j, 13, row_data["category"])
        ws.cell(6+j, 14, round(row_data["total_revenue_inr"], 0))

    pie = PieChart()
    pie.title   = "Revenue Share by Category"
    pie.style   = 10
    pie.width   = 18
    pie.height  = 14
    data_ref = Reference(ws, min_col=14, max_col=14, min_row=5, max_row=5+len(cat_df))
    cats_ref = Reference(ws, min_col=13, max_col=13, min_row=6, max_row=5+len(cat_df))
    pie.add_data(data_ref, titles_from_data=True)
    pie.set_categories(cats_ref)
    ws.add_chart(pie, "M14")

    # Conditional formatting for units sold
    ws.conditional_formatting.add(
        f"G5:G{4+len(df)}",
        ColorScaleRule(start_type="min", start_color="FEE2E2",
                       mid_type="percentile", mid_value=50, mid_color="FEF3C7",
                       end_type="max", end_color="D1FAE5")
    )




def build_demand(wb):
    ws = wb.create_sheet("📈 Demand Patterns")
    ws.sheet_view.showGridLines = False
    ws.sheet_properties.tabColor = C["purple"]
    ws.row_dimensions[1].height = 6
    set_col_widths(ws, {get_column_letter(i): 12 for i in range(1,20)})
    ws.column_dimensions["A"].width = 3

    banner(ws, 2, "ORDER DEMAND PATTERNS — HOURLY & DAILY", 14, bg=C["purple"], size=15)

    # Hourly table
    banner(ws, 4, "Hourly Order Volume & Fulfillment Time", 9, bg="3D2570", size=11)
    ph = load("peak_hours")
    hcols = [("B","Hour"),("C","Total Orders"),("D","Total Units"),
             ("E","Avg TAT (min)"),("F","Period")]
    header_row(ws, 5, hcols, bg="3D2570")

    period_colors = {
        "Morning Peak": "D1FAE5",
        "Evening Peak": "D1FAE5",
        "Night": "E8EFF6",
        "Afternoon Lull": "FFFBEB",
        "Off-Peak Morning": "F0F4FF",
    }
    for i, row_data in ph.iterrows():
        rv = 6 + i
        vals = [f"{int(row_data.hour):02d}:00", int(row_data.total_orders),
                int(row_data.total_units), row_data.avg_fulfillment_min, row_data.period_label]
        data_row(ws, rv, vals, bg="FFFFFF")
        pc = period_colors.get(str(row_data.period_label), "FFFFFF")
        for col in range(2, 7):
            ws.cell(rv, col).fill = fill(pc if i % 2 == 0 else "FFFFFF")

    # Line chart: orders by hour
    chart = LineChart()
    chart.title  = "Order Volume by Hour of Day"
    chart.style  = 10
    chart.y_axis.title = "Orders"
    chart.x_axis.title = "Hour"
    chart.width  = 22
    chart.height = 14
    data_ref = Reference(ws, min_col=3, max_col=3, min_row=5, max_row=5+len(ph))
    cats_ref = Reference(ws, min_col=2, max_col=2, min_row=6, max_row=5+len(ph))
    chart.add_data(data_ref, titles_from_data=True)
    chart.set_categories(cats_ref)
    ws.add_chart(chart, "H4")

    # Day-of-week table
    r2 = 7 + len(ph)
    banner(ws, r2, "Day-of-Week Performance", 7, bg="3D2570", size=11)
    dow = load("dow_performance")
    hcols2 = [("B","Day"),("C","Total Orders"),("D","Total Units"),
              ("E","Avg TAT (min)"),("F","UPH"),("G","Rank")]
    header_row(ws, r2+1, hcols2, bg="3D2570")
    dow_sorted = dow.copy()
    dow_sorted["rank"] = dow_sorted["total_orders"].rank(ascending=False).astype(int)
    for i, row_data in dow_sorted.iterrows():
        rv = r2 + 2 + i
        vals = [row_data.day_of_week, int(row_data.total_orders), int(row_data.total_units),
                row_data.avg_tat_min, row_data.overall_uph, f"#{int(row_data['rank'])}"]
        data_row(ws, rv, vals, bg="FFFFFF")

    # Bar chart: orders by day
    chart2 = BarChart()
    chart2.title  = "Orders by Day of Week"
    chart2.style  = 10
    chart2.width  = 22
    chart2.height = 14
    data2 = Reference(ws, min_col=3, max_col=3, min_row=r2+1, max_row=r2+1+len(dow_sorted))
    cats2 = Reference(ws, min_col=2, max_col=2, min_row=r2+2, max_row=r2+1+len(dow_sorted))
    chart2.add_data(data2, titles_from_data=True)
    chart2.set_categories(cats2)
    ws.add_chart(chart2, f"H{r2}")

    # Daily trend data bar
    ws.conditional_formatting.add(
        f"C6:C{5+len(ph)}",
        DataBarRule(start_type="min", start_value=0, end_type="max", end_value=None, color="5C3D99")
    )



def build_delivery(wb):
    ws = wb.create_sheet("🚚 Delivery Cost Analysis")
    ws.sheet_view.showGridLines = False
    ws.sheet_properties.tabColor = C["orange"]
    set_col_widths(ws, {"A":3,"B":16,"C":14,"D":14,"E":14,"F":14,"G":16,"H":18})
    ws.row_dimensions[1].height = 6

    banner(ws, 2, "DELIVERY COST & SLOT EFFICIENCY ANALYSIS", 8, bg=C["orange"], size=15)

    df = load("slot_cost_analysis")
    hcols = [("B","Delivery Slot"),("C","Deliveries"),("D","Avg Cost (₹)"),
             ("E","Avg Distance (km)"),("F","Avg Time (min)"),
             ("G","Total Cost (₹)"),("H","Success Rate (%)")]
    header_row(ws, 4, hcols, bg=C["orange"])

    for i, row_data in df.iterrows():
        rv = 5 + i
        vals = [row_data.delivery_slot, int(row_data.total_deliveries),
                row_data.avg_cost_inr, row_data.avg_distance_km,
                row_data.avg_time_min,
                round(row_data.total_cost_inr, 2),
                round(row_data.delivery_success_pct, 1)]
        data_row(ws, rv, vals, bg="FFFFFF")
        # Colour success rate
        sr = row_data.delivery_success_pct
        ws.cell(rv, 8).fill = fill("D1FAE5" if sr > 80 else ("FEF3C7" if sr > 70 else "FEE2E2"))

    # Bar chart: avg cost by slot
    chart = BarChart()
    chart.title  = "Avg Delivery Cost by Slot"
    chart.style  = 10
    chart.width  = 20
    chart.height = 14
    data_ref = Reference(ws, min_col=4, max_col=4, min_row=4, max_row=4+len(df))
    cats_ref = Reference(ws, min_col=2, max_col=2, min_row=5, max_row=4+len(df))
    chart.add_data(data_ref, titles_from_data=True)
    chart.set_categories(cats_ref)
    ws.add_chart(chart, "B10")

    # Delivery status table
    r2 = 11 + len(df)
    banner(ws, r2, "Delivery Status Summary", 5, bg="8B3A00", size=11)
    ds = load("delivery_status")
    hcols2 = [("B","Status"),("C","Count"),("D","% Share"),("E","Interpretation")]
    header_row(ws, r2+1, hcols2, bg="8B3A00")
    interp = {"Delivered": "✅ Successful", "Delayed": "⏳ SLA Breach",
              "Returned": "🔄 Return to WH", "Cancelled": "❌ Cancelled"}
    for i, row_data in ds.iterrows():
        rv = r2 + 2 + i
        vals = [row_data.status, int(row_data["count"]), f"{row_data.pct:.1f}%",
                interp.get(str(row_data.status), "—")]
        data_row(ws, rv, vals, bg="FFFFFF")

    # Pie: delivery status
    pie = PieChart()
    pie.title  = "Delivery Status Distribution"
    pie.style  = 10
    pie.width  = 18
    pie.height = 14
    data2 = Reference(ws, min_col=3, max_col=3, min_row=r2+1, max_row=r2+1+len(ds))
    cats2 = Reference(ws, min_col=2, max_col=2, min_row=r2+2, max_row=r2+1+len(ds))
    pie.add_data(data2, titles_from_data=True)
    pie.set_categories(cats2)
    ws.add_chart(pie, f"F{r2}")



def build_replenishment(wb):
    ws = wb.create_sheet("🔔 Replenishment Alerts")
    ws.sheet_view.showGridLines = False
    ws.sheet_properties.tabColor = C["red"]
    set_col_widths(ws, {"A":3,"B":10,"C":24,"D":14,"E":8,"F":13,"G":13,"H":12,"I":20,"J":22})
    ws.row_dimensions[1].height = 6

    banner(ws, 2, "⚠  REPLENISHMENT & REORDER ALERTS", 10, bg=C["red"], size=15)

    # Summary strip
    df_all = load("sku_velocity")
    out_of_stock = len(df_all[df_all["current_stock"] == 0])
    reorder_now  = len(df_all[df_all["stock_status"] == "REORDER NOW"])
    low_stock    = len(df_all[df_all["stock_status"] == "Low Stock"])

    tiles = [
        ("OUT OF STOCK", str(out_of_stock), C["red"]),
        ("REORDER NOW",  str(reorder_now),  C["orange"]),
        ("LOW STOCK",    str(low_stock),     C["yellow"]),
        ("ALL CLEAR",    str(len(df_all) - out_of_stock - reorder_now - low_stock), C["green"]),
    ]
    ws.row_dimensions[4].height = 10
    for i, (lbl, val, bg) in enumerate(tiles):
        col = 2 + i*2
        kpi_tile(ws, 5, col, lbl, val, bg)

    # Detailed alerts
    alerts = load("reorder_alerts")
    r2 = 9
    banner(ws, r2, "DETAILED REORDER REPORT", 10, bg="8B0000", size=12)
    hcols = [("B","SKU"),("C","Product Name"),("D","Category"),("E","Zone"),
             ("F","Stock"),("G","Reorder Level"),("H","Shortage"),
             ("I","Est. Reorder Cost (₹)"),("J","Alert Level")]
    header_row(ws, r2+1, hcols, bg="8B0000")

    row_bg = {"OUT OF STOCK": "FEE2E2", "REORDER NOW": "FEF3C7", "Low Stock": "FFFBEB"}
    for i, row_data in alerts.iterrows():
        rv = r2 + 2 + list(alerts.index).index(i)
        bg_key = "OUT OF STOCK" if "OUT" in str(row_data.alert_level) else \
                 "REORDER NOW" if "REORDER" in str(row_data.alert_level) else "Low Stock"
        vals = [row_data.sku_id, row_data.product_name, row_data.category,
                row_data.storage_zone, int(row_data.current_stock),
                int(row_data.reorder_level), int(row_data.shortage_units),
                f"₹{row_data.estimated_reorder_cost_inr:,.0f}", row_data.alert_level]
        data_row(ws, rv, vals, bg=row_bg.get(bg_key, "FFFFFF"))
        ws.cell(rv, 10).font = font(bold=True, color=C["red"] if "OUT" in str(row_data.alert_level) else C["orange"])

    # Zone summary
    zone_df = load("reorder_alerts").groupby("storage_zone").agg(
        items_to_reorder=("sku_id","count"),
        total_shortage=("shortage_units","sum"),
        total_cost=("estimated_reorder_cost_inr","sum")
    ).reset_index()

    r3 = r2 + 2 + len(alerts) + 2
    banner(ws, r3, "Reorder Summary by Zone", 5, bg=C["orange"], size=11)
    header_row(ws, r3+1, [("B","Zone"),("C","SKUs to Reorder"),("D","Total Shortage"),("E","Est. Cost (₹)")], bg=C["orange"])
    for i, row_data in zone_df.iterrows():
        rv = r3 + 2 + i
        vals = [row_data.storage_zone, int(row_data.items_to_reorder),
                int(row_data.total_shortage), f"₹{row_data.total_cost:,.0f}"]
        data_row(ws, rv, vals, bg="FFFFFF")



def main():
    wb = Workbook()
    wb.remove(wb.active)          # remove default empty sheet

    print("  Building sheets…")
    build_kpi(wb);           print("    ✓ KPI Summary")
    build_picker(wb);        print("    ✓ Picker Productivity")
    build_sku(wb);           print("    ✓ SKU Performance")
    build_demand(wb);        print("    ✓ Demand Patterns")
    build_delivery(wb);      print("    ✓ Delivery Cost Analysis")
    build_replenishment(wb); print("    ✓ Replenishment Alerts")

    out_path = "Warehouse_Operations_Dashboard.xlsx"
    wb.save(out_path)
    print(f"\n✅  Dashboard saved → {out_path}")

if __name__ == "__main__":
    main()
